geoadmin/service-alti

- alti/lib/validation/profile.py
- alti/tests/integration/test_profile.py
- alti/views/profile.py
- production.ini.in
Currently, if you set *nb_points* to 500, you effectively get *500* points. This PR defines a *default* and *max value* for *nb_points*.
Current situation (integration)
```
$ curl -s -H "Referer: http://toto.admin.ch" -H "Content-Type: application/json" \
"http://service-alti.int.bgdi.ch/rest/services/profile.json?geom=%7B%22type%22%3A%22LineString%22%2C%22coordinates%22%3A%5B%5B550050%2C206550%5D%2C%5B556950%2C204150%5D%2C%5B561050%2C207950%5D%5D%7D&nb_points=600" | jq '.'[].dist | wc -l
601
```
With this PR (/ltmom)
```
$ curl -s -I -H "Referer: http://toto.admin.ch" -H "Content-Type: application/json"  "http://service-alti.dev.bgdi.ch/ltmom/rest/services/profile.json?geom=%7B%22type%22%3A%22LineString%22%2C%22coordinates%22%3A%5B%5B550050%2C206550%5D%2C%5B556950%2C204150%5D%2C%5B561050% …
```
> Setting a hard limit for nb_points in profile

- apache/wsgi.conf.in
and supporting both apache 2.2 and 2.4 syntax. Returning a `403 Forbidden` and not an `500 Internal Error`
> Allow services for all

- Makefile
- requirements.txt
Due to some certificat issue, we cannot install with the distribution pip anymore.
Install modern pip from local, additional python module for SSL issue, and revert to older flake8
> Issue with install

- .gitignore
- Makefile
- alti/lib/validation/profile.py
- alti/subscribers.py
- alti/tests/integration/test_profile.py
- apache/wsgi.conf.in
- rc_dev
- rc_int
- rc_prod
- scripts/generate-linestring.py
- scripts/test-payload.sh
Evaluation for https://github.com/geoadmin/mf-chsdi3/issues/2702
`./scripts/test-payload.sh`
5300 coordinates is still fine but it takes up to 10 sec.
It seems that blocking at 150'000 content length would already be quite permissive. do you agree?
ping @gjn @davidoesch 
`Content-Length: 127487`
Then I have to find out why the `@` notation with curl doesn't work. Body is too big to be passed as a string to curl beyond that.
ping @procrastinatio could you give me a hint?
I would like to block it at Apache level.
https://github.com/geoadmin/mf-chsdi3/issues/2702
> Debugging for big linestring, limit geom size

- alti/lib/validation/profile.py
- alti/views/profile.py
- deploy/deploy-branch.cfg.in
- requirements.txt
To be able to checkout perf improvement with https://github.com/geoadmin/service-alti/pull/46
I need to be able to send Wanderweg profile (around 2000 points). With actual master it's not possible as this exceed URL max length when writing down this kind of GeoJSON into the URL.
In order to circumvent this, this PR make the profile service check the body of the HTTP request if no `geom` param is found in the URL.
> Accept geom in HTTP POST body

- alti/lib/profile_helpers.py
- alti/tests/functional/test_profile_helpers.py
- alti/tests/integration/test_profile.py
Always return the "old" JSON structure, but filling the now empty elevation_models with the new COMB values.
```
{
...
'alts': {
'COMB': ...,
'DTM2': ...,
'DTM25': ...
}
...
}
```
> Rollback changes made on profile JSON structure

- alti/lib/profile_helpers.py
- alti/tests/functional/test_profile_helpers.py
> Return an empty profile when SR is given and coordinates are out of bounds

- alti/lib/profile_helpers.py
As we don't have (yet) a CI that can run integration tests (I also forgot to run them before merging https://github.com/geoadmin/service-alti/pull/66 ) here is a little fix for what popped up during integration test
> Removing deleted methods usage

- Makefile
- alti/lib/profile_helpers.py
- alti/lib/raster/dbfutils.py
- alti/renderers.py
- alti/tests/integration/test_profile.py
I kept xrange in the code rather than already switchint to range (which is also supported in python2), because performance-wise, xrange is better in python2 than range (the comportment of range in python3 has been altered to be the same as xrange). This is ugly, but should be temporary.
I also put little TODOS to explain what is left to do to finish the transition. It's not much.
> support for python 3

- logging-cfg-dev.yml
- logging-cfg-local.yml
- logging-cfg-prod.yml
UTC time format is a better choice for the ELK (Elastic Logstash
Kibana).
See https://jira.swisstopo.ch/browse/BGDIINF_SB-1260
> BGDIINF_SB-1260: Use UTC time format in logging

- app/helpers/raster/shputils.py
- app/statistics/statistics.py
- dev_requirements.txt
- tests/unit_tests/test_profile.py
- wsgi.py
Due to a bug in pylint (see https://github.com/PyCQA/pylint/issues/2625)
some pylint false positive were reported which prevent PR to be merge (see #81).
```
app/helpers/profile_helpers.py:180:39: E1101: Instance of 'BaseGeometry' has no 'x' member; maybe 'xy'? (no-member)
```
This issue might also have been introduced by the silent update of astroid which pylint depends on. To avoid such sub-dependencies issue in future we should update the repo to use pipenv instead. This will be done in a next pr.
Updating pylint to the latest version seems to solve this issue. However it introduced other pylint suggestions.
With the upgrade of pylint 2 file descriptor leak has been found. They have been fixed using with statement. Other minor pylint issue has been fixed as well.
> BGDIINF_SB-1808: Fixed pylint false positive and FD leak

- app/routes.py
When the application crashed, the log did not contains any back trace,
but only a stringification of the exception which can be very short and
unusefull. For example if a KeyError is raised, str(e) would return only
the name of the key that cause the exception, which such info it is
almost impossible to know what cause the exception.
> Improved crash logging

- .pylintrc
- app/helpers/validation/profile.py
- app/routes.py
- tests/unit_tests/test_profile.py
- tests/unit_tests/test_profile_validation.py
If the request was done with an invalid content-type, then the service
returned a 400, "No 'geom' given, cannot create a profile without coordinates".
This was kind of misleading, for example when doing a request with curl without
specifying the content-type (curl used application/x-www-form-urlencoded) but
with valid payload.
The issue was that request.is_json in flask is set based on the content-type header
and not on the payload being a valid json.
> BGDIINF_SB-2197: Returns 415 in case of wrong content-type

- app/__init__.py
- app/routes.py
- tests/unit_tests/test_height.py
- tests/unit_tests/test_profile.py
The callback query parameter has two minor issues and was also not very efficient
when used on the profile.json endpoint.
The first issue was that if given to the profile.csv endpoint it would have
transformed the CSV output by wrapping it with the value of callback and
marked the output as javascript. However this was an invalid javascript output
as CSV is not a javascript valid syntax. This bug has been introduced with the
dockerization, before in this case the callback query was simply ignored. Now
it is not ignored but returns a 400 HTTP status.
The second minor issue, which was more a syntax sugar, was that using the callback
query, a useless LF character was added at the end of the json data.
The last issue was about efficiency especially used on a big data output (200 points). …
> BGDIINF_SB-2347: Fixed callback parameter responses

- app/routes.py
The profile.csv endpoint did not returned a well csv formed format, but
a python dictionary. This has been fixed also fixing the 203 answer
code.
> BGDIINF_SB-2378: Corrected the CSV output

- app/helpers/validation/__init__.py
- app/helpers/validation/height.py
- app/helpers/validation/profile.py
- app/routes.py
- tests/unit_tests/test_profile.py
Avoiding 500 error when the request parameters are invalid.
Only LineString and Point are supported as input geometry. Checking this
avoid later crash.
Removed also broad exception by using correct exception type.
Point and LineString shape `is_valid` is a property and not a function
and do not raise exception but simply return True or False. Before this
kind of invalid shape object where caught later by trying to guess the
srid.
> BGDIINF_SB-2238: Improved error handling - avoid 500 errors on bad request

- app/helpers/validation/profile.py
- tests/unit_tests/test_profile_validation.py
In case of a nb_points smaller than 2, the error message was that the value must
be smaller than 5000 which was missleading as 0 or -1 is smaller than 5000.
Now the error message says that the nb_points must be greater than 1.
> BGDIINF_SB-2347: Improved error message in case of invalid nb_points

- app/__init__.py
- app/helpers/url.py
- tests/unit_tests/__init__.py
- tests/unit_tests/base.py
- tests/unit_tests/test_base.py
- tests/unit_tests/test_checker.py
- tests/unit_tests/test_height.py
- tests/unit_tests/test_profile.py
- tests/unit_tests/test_profile_validation.py
Updated the cors header to accept every origin as it is a public api. Also added "Access-Control-Allow-Headers" and updated to unit tests to check for the presence of the CORS headers.
> BGDIINF_SB-2479: Now the CORS header accepts every origin. Also updated unit tests.

- Makefile
- app/helpers/validation/profile.py
- app/routes.py
- tests/unit_tests/test_profile.py
The profile.json|csv should have supported input as form url encoded. This
was not the case.
Now all input parameters can be given as POST body in
application/x-www-form-urlencoded form. The JSON body in opposite only
accept the geom parameter.
Url encoded form parameter overwrite the parameter in query string.
> BGDIINF_SB-2477: Fixed support for form url encoded input data

- Dockerfile
- app/helpers/raster/georaster.py
- app/routes.py
- tests/unit_tests/test_checker.py
On vhost we need to have curl in order to test the liveness probe. Curl can
be in future removed when migrating to k8s.
> BGDIINF_SB-2544: Added readiness probe and curl for liveness probe

- app/helpers/validation/__init__.py
- tests/unit_tests/test_height.py
with the latest data update the perimeter covered by swissalti has been increased. these changes are updating the service perimeter from:
`Extent: (2450000.000000, 1030000.000000) - (2900000.000000, 1350000.000000)`
to:
`Extent: (2385000.000000, 974000.000000) - (2935000.000000, 1404000.000000) `
> BGDIDIC-1950: increase perimeter
