geoadmin/service-alti

Makefile
alti/__init__.py
alti/static/robots.txt
apache/wsgi.conf.in
rc_dev
rc_int
rc_prod

Also this project should never be accessible to web crawlers.

Add missing robots file

---

production.ini.in

EFS is slower than EBS for profile by a factor of 5 to 10. (similar to lazy load EBS)

Put back EBS

---

alti/lib/raster/shputils.py

@loicgasser or @procrastinatio   . this should fix the build.

Makes linter happy

---

apache/wsgi.conf.in

Block access to height. DON'T DEPLOY TO PROD

---

deploy/deploy.cfg
requirements.txt

Add new prod target 

---

alti/tests/integration/test_height.py

New data in march 2017 makes the tests fail

Fixing tests

---

alti/tests/integration/test_height.py
alti/tests/integration/test_profile.py

@procrastinatio 
Today I'm going to sync the data on int as well

adaption of tests due to data update

---

alti/views/height.py
deploy/deploy.cfg

Int and prod on the new debian jessie line

New deployment targets

---

alti/__init__.py
alti/lib/profile_helpers.py
alti/lib/raster/georaster.py
alti/lib/validation/height.py
alti/lib/validation/profile.py
alti/tests/functional/test_profile_helpers.py
alti/tests/integration/test_height.py
alti/tests/integration/test_profile.py
alti/views/height.py
alti/views/profile.py

Keep only COMB

---

alti/lib/raster/georaster.py

@pakb can you please review, merge and deploy to int.
thank you!

fix wrong data path

---

alti/lib/raster/georaster.py

Was generating random concurrency related errors. Reverting back to what was there before https://github.com/geoadmin/service-alti/pull/46 (keeping the close on delete, doesn't hurt if something went wrong during reading)
fixes https://github.com/geoadmin/service-alti/issues/65

Close files after value is read

---

buildspec.yml

Need to apply https://git.swisstopo.admin.ch/camptocamp/terraform-chtopo-bgdi-builder/merge_requests/7
See https://jira.swisstopo.ch/browse/KOGIS_PRJ-623

Running codebuild

---

.pylintrc
README.md
app/helpers/__init__.py
logging-cfg-dev.yml
logging-cfg-local.yml
logging-cfg-prod.yml
requirements.txt
wsgi.py

Now logging on DEV and PROD can be done in JSON format.

BGDIINF_SB-1260: Added logging configuration

---

.github/workflows/main.yml
Dockerfile
Makefile
README.md
app/routes.py
app/version.py

Now the service uses SemVer auto versioning.

BGDIINF_SB-1535: Added SemVer versioning

---

Makefile
buildspec.yml

Now we use the ECR docker registry instead of dockerhub.

BGDIINF_SB-1839: setup ECR docker registry

---

.dockerignore
Dockerfile
README.md
app/__init__.py
app/helpers/raster/dbfutils.py
app/helpers/raster/georaster.py
app/helpers/raster/shputils.py
app/helpers/url.py
app/helpers/validation/profile.py
app/routes.py
app/settings.py
service_alti.py
wsgi.py

Fixed a python3 issues with binary strings and did fixes some various issue for deployment on k8s.

BGDIINF_SB-1893: Made the number of wsgi worker configurable

---

app/helpers/profile_helpers.py

Altitude header is missing in the `profile.csv` output.

Fix csv profile header

---

Pipfile
Pipfile.lock
app/__init__.py
app/helpers/__init__.py
app/helpers/raster/dbfutils.py
app/helpers/raster/georaster.py
app/helpers/raster/shputils.py
app/helpers/url.py
app/helpers/validation/profile.py
app/routes.py
app/statistics/statistics.py
tests/unit_tests/test_profile.py
tests/unit_tests/test_profile_helpers.py
wsgi.py

BGDIINF_SB-2197: Updated python packages and clean up unused packages

---

app/helpers/validation/height.py
app/settings.py

This also allow to improve the coding maintenance on the end to end test side.

BGDIINF_SB-2347: Improved error message on invalid srid

---

app/routes.py

When adding a query parameter with =False it was treated as True.

BGDIINF_SB-2381: Fixed boolean query parameters

---

.pylintrc
Pipfile
Pipfile.lock
app/helpers/profile_helpers.py
logging-cfg-local.yml

Using generator in Sum() instead of list comprehension is slightly more efficient.

BGDIINF_SB-2520: Consolidate logging and fixed pylint recommendation
